Change sudobg to return PID number

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -391,38 +391,40 @@ function _spinner() {
     case $1 in
         start)
             # calculate the column where spinner and status msg will be displayed
-            let column=$(tput cols)-${#2}-8
+            #let column=$(tput cols)-${#2}-8
             # display message and position the cursor in $column column
-            echo -ne ${2}
-            printf "%${column}s"
+            #echo -ne ${2}
+            #printf "%${column}s"
 
             # start spinner
-            i=1
-            sp='\|/-'
-            delay=${SPINNER_DELAY:-0.15}
+            #i=1
+            #sp='\|/-'
+            #delay=${SPINNER_DELAY:-0.15}
 
-            while :
-            do
-                printf "\b${sp:i++%${#sp}:1}"
-                sleep $delay
-            done
+            #while :
+            #do
+            #    printf "\b${sp:i++%${#sp}:1}"
+            #    sleep $delay
+            #done
+            spinner _sp_pid ${2}
+            
             ;;
         stop)
-            if [[ -z ${3} ]]; then
-                echo "spinner is not running.."
-                exit 1
-            fi
+            #if [[ -z ${3} ]]; then
+            #    echo "spinner is not running.."
+            #    exit 1
+            #fi
 
             kill $3 > /dev/null 2>&1
 
             # inform the user uppon success or failure
-            echo -en "\b["
-            if [[ $2 -eq 0 ]]; then
-                echo -en "${green}${on_success}${nc}"
-            else
-                echo -en "${red}${on_fail}${nc}"
-            fi
-            echo -e "]"
+            #echo -en "\b["
+            #if [[ $2 -eq 0 ]]; then
+            #    echo -en "${green}${on_success}${nc}"
+            #else
+            #    echo -en "${red}${on_fail}${nc}"
+            #fi
+            #echo -e "]"
             ;;
         *)
             echo "invalid argument, try {start/stop}"
