Add previous held packages check.

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -324,6 +324,14 @@ function update(){
 	then
 		error ${LINENO} "An error occured while elevating permissions." $EXIT_STAT
 	fi
+	echo -e "${PLUS} Testing for previous help packages and trying to correct any found."
+	$SUDO apt-get -qqf install &>/dev/null
+	EXIT_STAT=$?
+	if [ $EXIT_STAT -ne 0 ]
+	then
+		error ${LINENO} "An error occured while examining possible apt held packages." $EXIT_STAT
+	fi
+	echo -e " \_${Green}Passed${Reg}\n"
 	start_spinner "Updating package cache . . ."
 		$SUDO apt-get update &>/dev/null
 	stop_spinner 0
