Shellcheck linting

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -10,26 +10,30 @@ whip_msg(){
 
 chk_root(){
 	if [[ $EUID -eq 0 ]]; then
+		# shellcheck disable=SC2154
 		whip_msg  "${w_title_three}" "${w_msg_three}"
 	fi
 }
 
 chk_sudoer(){
-	grep 'sudo' /etc/group | grep $USER > /dev/null 2>&1
+	grep 'sudo' /etc/group | grep "$USER" > /dev/null 2>&1
 	EXIT_STAT=$?
 	if [ $EXIT_STAT -ne 0 ]
 	then
-		error "Sudo: Not found" "The user was not found in the sudo group. Cannot continue." 1 
+		error "Sudo: Not found" "The user was not found in the sudo group. Cannot continue." 1
 	fi
 }
 
 get_arch(){
+	# shellcheck disable=SC2154
 	echo -en "${Cyan} \_ Determining CPU type: "
 	if [ "$(getconf LONG_BIT)" == "64" ]; then arch=amd64; else arch=i386; fi
+	# shellcheck disable=SC2154
 	echo -e "${Yellow}${arch}${Reg}"
 }
 
 reqexit(){
+	# shellcheck disable=SC2154
 	echo -e "${Red}Response not in the offered list of options. Interpreted as an exit request. Exiting.${Reg}"
 	exit 0
 }
@@ -37,6 +41,7 @@ reqexit(){
 check_qt(){
 	printf '\t%-24s' "QT4 or QT5"
 	if pkg-config --exists Qt5Core || pkg-config --exists QtCore; then \
+		# shellcheck disable=SC2154
 		echo -e "${Green}Found${Reg}"; \
 		return 0; \
 	else \
@@ -46,9 +51,10 @@ check_qt(){
 }
 
 check_deps(){
-	for dep in $(echo ${DEPENDENCIES} | tr ' ' $'\n'); do
+	for dep in $(echo "${DEPENDENCIES}" | tr ' ' $'\n'); do
 		printf '\t%-24s' "${dep}"
-		if [[ -z `dpkg -l | grep "^ii  $dep"` ]]; then
+		#if [[ -z $(dpkg -l | grep "^ii  $dep") ]]; then
+		if ! ( dpkg -l | grep -q "^ii  $dep" ); then
 			echo -e "${Red}Not Found${Reg}"
 			UPDATENEEDED=1
 			TOINSTALL+="${dep} "
@@ -76,40 +82,40 @@ check_qt5(){
 }
 
 cleanup(){
-	rm $OUTPUT -f
+	rm "$OUTPUT" -f
 }
 
 get_ubuntu_list(){
-	local FILES=($(curl -s ${BASEURL} | grep "v${MINVER}" | cut -d '>' -f 7 | awk '{print substr($0,1, length($0)-4)}'))
+	local FILES=($(curl -s "${BASEURL}" | grep "v${MINVER}" | cut -d '>' -f 7 | awk '{print substr($0,1, length($0)-4)}'))
 	local FILTERED_FILES=(${FILES[@]/*$RC_FILTER*/})
-	
+
 	NUMEL=${#FILTERED_FILES[@]}
-	
-	for (( i=${NUMEL}; i>=0; i-- )); 
+
+	for (( i="${NUMEL}"; i>=0; i-- ));
 	do
 		TOTAL="${TOTAL}\n${FILTERED_FILES[i]}"
 		DOWN="${DOWN}\n${FILTERED_FILES[i]}"
 	done
-	
+
 	echo -ne "\n"
-	for ver in $(echo -e $TOTAL); do
+	for ver in $(echo -e "$TOTAL"); do
 		((COUNT++))
-		printf ' %-3s Linux %-20s' "${COUNT})" "`echo ${ver##*'/'}|cut -d '>' -f 7 | sed 's/-$//'`"
+		printf ' %-3s Linux %-20s' "${COUNT})" "$(echo "${ver##*'/'}" | cut -d '>' -f 7 | sed 's/-$//')"
 		[ $((COUNT%4)) -eq 0 ] && echo -e -n '\n'
 	done
-	
+
 	NUMOPTS=$COUNT
 	COUNT=0
 }
 
 print_kernels_ubu(){
-	if [ "`basename "$0"`" = "update_ubuntu_kernel.sh" ]; then
+	if [ "$(basename "$0")" = "update_ubuntu_kernel.sh" ]; then
 		echo -e "${Cyan} \_ Precompiled kernels available from ${Yellow}kernel.ubuntu.com:${Reg}"
 		get_ubuntu_list
-	elif [ "`basename "$0"`" = "bats-exec-test" ]; then
+	elif [ "$(basename "$0")" = "bats-exec-test" ]; then
 		get_ubuntu_list
 	else
-		error "Func: Print_kernel" "Logic error in parsing latest kernel. Exiting." 1 
+		error "Func: Print_kernel" "Logic error in parsing latest kernel. Exiting." 1
 	fi
 }
 
@@ -117,22 +123,22 @@ get_debian_list(){
 	local FILES=($(curl -s https://kernel.org | grep "Download complete tarball" | cut -d '.' -f 2- | cut -d '"' -f 1 ))
 	local FILTERED_FILES=(${FILES[@]/*$RC_FILTER*/})
 
-	for ver in ${FILTERED_FILES[@]}; do
+	for ver in "${FILTERED_FILES[@]}"; do
 		TOTAL="${TOTAL} https://$ver"
 	done
 
 	# Has full URL file names
 	TOTAL=(${TOTAL[@]})
 
-	for ver in ${TOTAL[@]}; do
-		LIST="${LIST} `echo ${ver##*'/'}`"
+	for ver in "${TOTAL[@]}"; do
+		LIST="${LIST} ${ver##*'/'}"
 	done
 
 	ARR_LIST=(${LIST[@]})
 	ARR_END=${#ARR_LIST[@]}
-	NEW_ARR_END=$((${ARR_END}*2-1))
+	NEW_ARR_END=$((ARR_END*2-1))
 
-	for (( i=${NEW_ARR_END}; i>0; i=i-2 ))
+	for (( i=NEW_ARR_END; i>0; i=i-2 ))
 	do
 		iOLD=$(((i-1)/2))
 		ARR_LIST[i]=" "
@@ -143,7 +149,7 @@ get_debian_list(){
 # Not using whiptail for Ubuntu - too many selection choices
 select_kernel_deb(){
 	get_debian_list
-	
+
 	# Override if using 'LATEST' else whiptail menu
 	if [[ $USE_LATEST -eq 1 ]] ; then
 		if [[ $1 != "quiet" ]]; then
@@ -151,11 +157,11 @@ select_kernel_deb(){
 		fi
 		OPTION="${ARR_LIST}"
 	else
-		OPTION=$(whiptail --title "Available Kernels" --backtitle "${BACKTITLE}" --menu "Select kernel arhive to download" 20 80 ${ARR_END} "${ARR_LIST[@]}" 3>&1 1>&2 2>&3)
+		OPTION=$(whiptail --title "Available Kernels" --backtitle "${BACKTITLE}" --menu "Select kernel arhive to download" 20 80 "${ARR_END}" "${ARR_LIST[@]}" 3>&1 1>&2 2>&3)
 	fi
 
-	if [[ -n ${OPTION} ]]; then 
-		TGTFILE=`printf "%s\n" "${TOTAL[@]}" | grep "${OPTION}"`; 
+	if [[ -n ${OPTION} ]]; then
+		TGTFILE=$(printf "%s\n" "${TOTAL[@]}" | grep "${OPTION}");
 	else
 		whip_msg  "Select Kernel Cancel" "No kernel was selected.\nExiting and cleaning up."
 		exit 0
@@ -164,20 +170,22 @@ select_kernel_deb(){
 
 get_kernel_archive(){
 	TEMPFILES+=( "${OUTPUT}" )
+	# shellcheck disable=SC2016
 	eval wget -O "${OUTPUT}" "${TGTFILE}" 2>&1 | \
 	stdbuf -o0 awk '/[.] +[0-9][0-9]?[0-9]?%/ { print substr($0,63,3) }' | \
 	whiptail --title "Download Kernel Archive" --backtitle "${BACKTITLE}" --gauge "Downloading kernel archive . . ." 7 70 0
-	
+
 	err=$?
 	if [ $err -ne 0 ]
 	then
 		error "Func: print_kernels" "Download source failure." $err
 	fi
-			
-	SIGNurl=`sed 's/.xz/.sign/g' <<< ${TGTFILE}`
-	SIGNfile=`sed 's/.xz/.xz.sign/g' <<< ${OPTION}`
+
+	SIGNurl=$(sed 's/.xz/.sign/g' <<< ${TGTFILE})
+	SIGNfile=$(sed 's/.xz/.xz.sign/g' <<< ${OPTION})
 
 	TEMPFILES+=( "${SIGNfile}" )
+	# shellcheck disable=SC2016
 	wget -O "${SIGNfile}" "${SIGNurl}" 2>&1 | \
 	stdbuf -o0 awk '/[.] +[0-9][0-9]?[0-9]?%/ { print substr($0,63,3) }' | \
 	whiptail --title "Download Kernel Archive" --backtitle "${BACKTITLE}" --gauge "Downloading signature file . . ." 7 70 0
@@ -190,22 +198,18 @@ select_kernel_ubu(){
 	else
 		echo -n -e "\n\nSelect your desired kernel: "
 		read INPUT
-	
-		# Check for non-integer
-		if ! [ $INPUT -eq $INPUT 2>/dev/null ]; then
-			reqexit
-		fi
-		# Check for non-offerred option
-		if [ $INPUT -gt $NUMOPTS ]; then
+
+		# Check for offered choices
+		if [[ $((INPUT)) != $INPUT ]] || [ "$INPUT" -gt $NUMOPTS ]; then
 			reqexit
 		fi
 	fi
 
 	# Prompt for Ubuntu Low Latency kernel
-	if [ "`basename "$0"`" = "update_ubuntu_kernel.sh" ]; then
+	if [ "$(basename "$0")" = "update_ubuntu_kernel.sh" ]; then
 		echo ""
 
-		# Set low latency default to no	
+		# Set low latency default to no
 		read -p "Do you want the lowlatency kernel? (y/[n]):" lowlatency
 		case "$lowlatency" in
 		   y* | Y*) lowlatency=1 ;;
@@ -213,17 +217,19 @@ select_kernel_ubu(){
 		esac
 
 		echo ""
-	fi	
+	fi
 }
 
 get_precompiled_ubu_kernel(){
 	get_arch
-	for ver in $(echo -e $TOTAL); do
+	# shellcheck disable=SC2128
+	for ver in $(echo -e "$TOTAL"); do
 		((COUNT++))
-		if [ $COUNT -eq $INPUT ]; then
-			for verd in $(echo -e $DOWN); do
+		if [ $COUNT -eq "$INPUT" ]; then
+			# shellcheck disable=SC2034
+			for verd in $(echo -e "$DOWN"); do
 				((COUNTD++))
-				if [ $COUNTD -eq $INPUT ]; then
+				if [ $COUNTD -eq "$INPUT" ]; then
 					# Download Kernel
 					if [ ${lowlatency} -eq 0 ]; then
 						KTYPE="generic"
@@ -231,10 +237,11 @@ get_precompiled_ubu_kernel(){
 						KTYPE="lowlatency"
 					fi
 					echo -e "${Cyan} \_ Locating source of ${ver} ${KTYPE} kernel packages.${Reg}"
-					
-					RSLT=`lynx -dump -listonly -dont-wrap-pre ${BASEURL}${ver} | grep "$1" | grep "$2" | grep "$arch" | grep -v "BUILD.LOG" | cut -d " " -f 4`
-			
+
+					RSLT=$(lynx -dump -listonly -dont-wrap-pre "${BASEURL}""${ver}" | grep "$1" | grep "$2" | grep "$arch" | grep -v "BUILD.LOG" | cut -d " " -f 4)
+
 					if [[ -z ${RSLT} ]]; then
+						# shellcheck disable=SC2154
 						whip_msg "${w_title_two}" "${w_msg_two}"
 						exit
 					else
@@ -242,16 +249,16 @@ get_precompiled_ubu_kernel(){
 						get_ubu_files ${KTYPE} header
 						get_ubu_files ${KTYPE} image
 					fi
-				fi				
+				fi
 			done
 		fi
 	done
 	echo -e "${Cyan} \_ Done${Reg}\n"
 }
-
 get_ubu_shared_header(){
 	TEMPFILES+=( "${ver}" )
-	eval wget $(lynx -dump -listonly -dont-wrap-pre ${BASEURL}${ver} | grep all | cut -d ' ' -f 4) 2>&1 | \
+	# shellcheck disable=SC2016
+	eval wget "$(lynx -dump -listonly -dont-wrap-pre "${BASEURL}""${ver}" | grep all | cut -d ' ' -f 4)" 2>&1 | \
 	stdbuf -o0 awk '/[.] +[0-9][0-9]?[0-9]?%/ { print substr($0,63,3) }' | \
 	whiptail --title "Download Precompiled Ubuntu Kernel Packages" --backtitle "${BACKTITLE}" --gauge "Downloading ${ver} shared header . . ." 7 70 0
 	err=$?
@@ -263,7 +270,8 @@ get_ubu_shared_header(){
 
 get_ubu_files() {
 	TEMPFILES+=( "${ver}" )
-	eval wget $(lynx -dump -listonly -dont-wrap-pre ${BASEURL}${ver} | grep "$1" | grep "$2" | grep "$arch" | cut -d ' ' -f 4) 2>&1 | \
+	# shellcheck disable=SC2016
+	eval wget "$(lynx -dump -listonly -dont-wrap-pre "${BASEURL}""${ver}" | grep "$1" | grep "$2" | grep "$arch" | cut -d ' ' -f 4)" 2>&1 | \
 	stdbuf -o0 awk '/[.] +[0-9][0-9]?[0-9]?%/ { print substr($0,63,3) }' | \
 	whiptail --title "Download Precompiled Ubuntu Kernel Packages" --backtitle "${BACKTITLE}" --gauge "Downloading ${ver} ${1} ${2} . . ." 7 70 0
 
@@ -275,7 +283,7 @@ get_ubu_files() {
 }
 
 install_key(){
-    gpg --keyserver pgp.mit.edu --recv-keys $CHK_ID --keyserver
+    gpg --keyserver pgp.mit.edu --recv-keys "$CHK_ID" --keyserver
 }
 
 ######
@@ -284,10 +292,11 @@ install_key(){
 spinner(){
 	local pid=$1
 	local delay=0.175
-	local spinstr='|/-\'
+	local spinstr="|/-\\"
 	tput civis;
 	local infotext=$2
-	while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
+	# shellcheck disable=SC2143
+	while [ "$(ps a | awk '{print $1}' | grep "$pid")" ]; do
 		local temp=${spinstr#?}
 		printf "[%c] %s" "$spinstr" "$infotext"
 		local spinstr=$temp${spinstr%"$temp"}
@@ -316,7 +325,7 @@ function update(){
 		error ${LINENO} "An error occured while elevating permissions." $EXIT_STAT
 	fi
 	start_spinner "Updating package cache . . ."
-		$SUDO apt-get update &>/dev/null 
+		$SUDO apt-get update &>/dev/null
 	stop_spinner 0
 	clearline
 	echo -e "${PLUS} Updating package cache . . ."
@@ -324,7 +333,7 @@ function update(){
 	for dep in ${TOINSTALL}
 	do
 		start_spinner "Installing ${dep} . . ."
-			$SUDO apt-get -qq -y install ${dep} &>/dev/null
+			$SUDO apt-get -qq -y install "${dep}" &>/dev/null
 		stop_spinner 0
 		clearline
 	done
@@ -339,7 +348,7 @@ function update(){
 countdown(){
 	local txt=$1
 	local secs=$2
-	while [ $secs -gt 0 ]; do
+	while [ "$secs" -gt 0 ]; do
 	echo -ne "$txt $secs\033[0K\r"
 	sleep 1
 	: $((secs--))
@@ -349,6 +358,7 @@ countdown(){
 sudobg() {
 	$SUDO echo ""
   	$SUDO "$@" > /dev/null 2>&1 &
+	# shellcheck disable=SC2034
 	BGPID=$!
 }
 
@@ -359,18 +369,19 @@ cleanupfiles() {
 }
 trap cleanupfiles 0
 
+# shellcheck disable=SC2120
 check_sign(){
 	start_spinner "Checking archive signature . . ."
-    	CHK_SIGN=`unxz -c ${OUTPUT} | gpg --verify ${SIGNfile} - 2>&1`
-    	CHK_SIGN_MISS_SIG=`grep -o 'public key not found' <<<$CHK_SIGN`
-    	CHK_ID=`grep -Po -- 'RSA key ID \K\w*' <<< "$CHK_SIGN"`
+	CHK_SIGN=$(unxz -c "${OUTPUT}" | gpg --verify "${SIGNfile}" - 2>&1)
+	CHK_SIGN_MISS_SIG=$(grep -o 'public key not found' <<<$CHK_SIGN)
+	CHK_ID=$(grep -Po -- 'RSA key ID \K\w*' <<< "$CHK_SIGN")
 	stop_spinner 0
 	clearline
 	echo -en "\e[1A"
 	echo -e "\n${PLUS} Checking archive signature . . ."
-	
+
     if [[ "$CHK_SIGN_MISS_SIG" == "public key not found" ]] ; then
-		if [[ "${1}" == "add" ]]; then
+		if [ $# -ne 0 ] && [[ "${1}" == "add" ]]; then
 			INSTALL_ID="y"
 		else
 			echo -e "\n[!] The public key for this file was not found in your PGP store."
@@ -378,29 +389,30 @@ check_sign(){
 			echo -e "    [Y]es  - Install the RSA key ID for ${Yellow}$CHK_ID${Reg}"
 			echo -e "    [n]o   - Do NOT install ID and EXIT"
 			echo -e "    [s]kip - Do NOT install ID and CONTINUE"
-		
+
 			echo -n -e "\n\nSelect your desired action: "
 			read INSTALL_ID
 		fi
-    
+
         case $INSTALL_ID in
-            [Nn]*) 
+            [Nn]*)
                 echo -e "NO - Exiting"
                 exit 0;
                 ;;
-            [Ss]*) 
+            [Ss]*)
                 echo -e "SKIP - Skipping GPG signature check."
                 ;;
             *) echo -e "YES - Installing new GPG key and checking archive."
                 install_key
+				# shellcheck disable=SC2119
                 check_sign
         esac
     else
-        CHK_SIGN_VALID=`grep -Po -- 'Good signature from' <<< "$CHK_SIGN"`
+        CHK_SIGN_VALID=$(grep -Po -- 'Good signature from' <<< "$CHK_SIGN")
         if [[ "$CHK_SIGN_VALID" == "Good signature from" ]] ; then
             echo -e " \_ Signature validated: ${Green}$CHK_ID${Reg}\n"
         else
-			error "Func: chk_sign" "Signature invalid. Exiting." 1 
+			error "Func: chk_sign" "Signature invalid. Exiting." 1
         fi
     fi
 }
@@ -423,7 +435,7 @@ function _spinner() {
     case $1 in
         start)
 			local delay=0.175
-			local spinstr='|/-\'
+			local spinstr="|/-\\"
 			tput civis;
 			local infotext=$2
 			while :
@@ -438,11 +450,11 @@ function _spinner() {
 				done
 			done
 			printf " \b\b\b\b"
-			tput cnorm;        
+			tput cnorm;
             ;;
         stop)
-            kill $3
-			wait $3 2>/dev/null
+            kill "$3"
+			wait "$3" 2>/dev/null
             ;;
         *)
             echo "invalid argument, try {start/stop}"
@@ -466,11 +478,11 @@ function stop_spinner() {
 
 function center-text() {
 	function get_width () {
-    	echo "$(wc -L <<< "$1")"
+    	wc -L <<< "$1"
 	}
 	function multi_space() {
 		num=$1
-		if [ $num -le 0 ]; then
+		if [ "$num" -le 0 ]; then
 			echo ""
 			return
 		fi
@@ -509,18 +521,19 @@ chk_version (){
 	CURVER=$(wget -O- -q https://raw.github.com/mtompkins/linux-kernel-utilities/master/version)
 	LOCVER=$(cat "version")
 	if [[ "${CURVER}" != "${LOCVER}" ]]; then
+		# shellcheck disable=SC2154
 		if ! (whiptail --yesno --defaultno --title "${w_title_four}" "${w_msg_four}" 20 80); then
 			whip_msg  "Exiting for update" "Exiting and cleaning up."
 			exit 0
 		fi
 	fi
-	
+
 
 }
 
 show_version (){
-	revisioncount=`git log --oneline | wc -l`
-	projectversion=`git describe --tags --long`
+	revisioncount=$(git log --oneline | wc -l)
+	projectversion=$(git describe --tags --long)
 	echo "Version: $projectversion-$revisioncount"
 }
 
@@ -528,6 +541,7 @@ function isremote(){
     if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
         SESSION_TYPE=remote/ssh
     else
+		# shellcheck disable=SC2034
         case $(ps -o comm= -p $PPID) in
             sshd|*/sshd) SESSION_TYPE=remote/ssh;;
         esac
