Permission changes

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -2,6 +2,16 @@
 
 # Requires `colors` - sourced in `functions`
 
+chk_sudoer(){
+	$SUDO grep $USER /etc/sudoers > /dev/null 2>&1
+	EXIT_STAT=$?
+	if [ $EXIT_STAT -ne 0 ]
+	then
+		error "Sudoers: Not found" "The user was not found in the sudoers group. Cannot continue with this account." 1 
+	fi
+	
+}
+
 get_arch(){
 	echo -en "${Cyan} \_ Determining CPU type: "
 	if [ "$(getconf LONG_BIT)" == "64" ]; then arch=amd64; else arch=i386; fi
